'------------------------------------------------------------------------------
' <auto-generated>
'     此代码由工具生成。
'     运行时版本:4.0.30319.42000
'
'     对此文件的更改可能会导致不正确的行为，并且如果
'     重新生成代码，这些更改将会丢失。
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    '此类是由 StronglyTypedResourceBuilder
    '类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    '若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    '(以 /str 作为命令选项)，或重新生成 VS 项目。
    '''<summary>
    '''  一个强类型的资源类，用于查找本地化的字符串等。
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Spec
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  返回此类使用的缓存的 ResourceManager 实例。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("FV.Spec", GetType(Spec).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  使用此强类型资源类，为所有资源查找
        '''  重写当前线程的 CurrentUICulture 属性。
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  查找类似 - 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 其他() As String
            Get
                Return ResourceManager.GetString("其他", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 其他图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("其他图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''Absorbed Energy
        '''(10*10*55,20℃,KU2)
        '''≥55J(69J/cm²);
        '''注1:J/cm²=吸收能量(J)/0.8
        '''注2:冲击缺口深度2mm 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 冲击功S48CG() As String
            Get
                Return ResourceManager.GetString("冲击功S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 冲击功S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冲击功S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''Absorbed Energy
        '''(10*10*55,20℃,KU2)
        '''≥55J(69J/cm²);
        '''注1:J/cm²=吸收能量(J)/0.8
        '''注2:冲击缺口深度2mm 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 冲击功S48CVOLVO() As String
            Get
                Return ResourceManager.GetString("冲击功S48CVOLVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 冲击功S48CVOLVO图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("冲击功S48CVOLVO图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 化学成分42CrMoG Spc:
        '''碳(C)/%  0.38~0.45
        '''硅(Si)/% 0.40 Max
        '''锰(Mn)/% 0.60~0.90
        '''磷(P)/% 0.025max
        '''硫(S)/% 0.025max
        '''铬(Cr)/% 0.9~1.20
        '''钼(Mo)/% 0.15~0.30
        '''Ni- 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分42CrMoG() As String
            Get
                Return ResourceManager.GetString("化学成分42CrMoG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分42CrMoG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("化学成分42CrMoG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 化学成分S48CG SPEC:
        '''碳C /0.48~0.51%
        '''硅Si /0.15~0.35%
        '''锰Mn /0.80~0.95%
        '''磷P /0~0.02%
        '''硫S /0.007~0.015%
        '''铬Cr /0.15~0.25%
        '''镍Ni /0~0.2%
        '''钼Mo /≤0.2%
        '''铜Cu /0~0.3% 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分S48CG() As String
            Get
                Return ResourceManager.GetString("化学成分S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("化学成分S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 化学成分S48CG SPEC:
        '''碳(C)/%  0.48~0.51
        '''硅(Si)/% 0.15~0.35
        '''锰(Mn)/% 0.80~0.9
        '''磷(P)/% 0~0.002
        '''硫(S)/% 0.007~0.015
        '''铜(Cu)/% 0~0.3
        '''铬+镍(Ni+Cr)/% Max.0.35
        '''铝(Al)/% 0.010~0.04
        '''钼(Mo)/% Max 0.2 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分VOLVO() As String
            Get
                Return ResourceManager.GetString("化学成分VOLVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 化学成分VOLVO图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("化学成分VOLVO图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''抗拉强度Rm/Mpa
        '''Tensile Strength  ≥740;
        '''屈服强度(Rp0.2)  ReL/MPa  ≥540;
        '''断后伸长率A/%
        '''Percentage elongation after fracture ≥15;
        '''断面收缩率Z/%
        '''Percentage reduction of area ≥40; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 拉伸试验S48CG() As String
            Get
                Return ResourceManager.GetString("拉伸试验S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 拉伸试验S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("拉伸试验S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''抗拉强度Rm/Mpa
        '''Tensile Strength  ≥675;
        '''下屈服强度ReL/MPa;
        '''Lower yield strength ≥500;
        '''断后伸长率A/%
        '''Percentage elongation after fracture ≥15;
        '''断面收缩率Z/%
        '''Percentage reduction of area ≥40; 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 拉伸试验S48CVOLVO() As String
            Get
                Return ResourceManager.GetString("拉伸试验S48CVOLVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 拉伸试验S48CVOLVO图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("拉伸试验S48CVOLVO图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''金相检验
        '''Metallographic Test 晶粒度(Grain size) ≥5级 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 晶粒度S48CG() As String
            Get
                Return ResourceManager.GetString("晶粒度S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 晶粒度S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("晶粒度S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''金相检验
        '''Metallographic Test 晶粒度(Grain size) ≥6级 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 晶粒度S48CVOLVO() As String
            Get
                Return ResourceManager.GetString("晶粒度S48CVOLVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 晶粒度S48CVOLVO图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("晶粒度S48CVOLVO图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 SPEC:
        '''硬度(HBW10/3000)
        '''Hardness: 212~277 HB 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 硬度试验S48CG() As String
            Get
                Return ResourceManager.GetString("硬度试验S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 硬度试验S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("硬度试验S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 锻造流程图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("锻造流程图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 非金属夹杂物S48CG SPEC:
        '''非金属夹杂物
        '''Non-metallic Inclusions
        '''A类: 细系≤2.5级,粗系≤1.5级;
        '''B类: 细系≤2.5级,粗系≤1.5级;
        '''C类: 细系≤2.5级,粗系≤1.5级;
        '''D类: 细系≤2.0级,粗系≤1.5级.
        '''Type A:Thin series≤Grade2.5,Thick series≤Grade 1.5;
        '''Type B:Thin series≤Grade2.5,Thick series≤Grade 1.5;
        '''Type C:Thin series≤Grade2.5,Thick series≤Grade 1.5;
        '''Type D:Thin series≤Grade2.0,Thick series≤Grade 1.5. 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 非金属夹杂物S48CG() As String
            Get
                Return ResourceManager.GetString("非金属夹杂物S48CG", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 非金属夹杂物S48CG图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("非金属夹杂物S48CG图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  查找类似 非金属夹杂物S48C VOLVO  SPEC:
        '''Non-metallic Inclusions
        '''JIS G 0555
        '''da &lt;0.15,d(B+C)&lt;0.10 DT &lt;0.25
        '''
        '''注:客户允许按照ISO 4967:2013 Method A 检测,但无标准要求,需要自己判定 的本地化字符串。
        '''</summary>
        Friend Shared ReadOnly Property 非金属夹杂物S48CVOLVO() As String
            Get
                Return ResourceManager.GetString("非金属夹杂物S48CVOLVO", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  查找 System.Drawing.Bitmap 类型的本地化资源。
        '''</summary>
        Friend Shared ReadOnly Property 非金属夹杂物S48CVOLVO图() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("非金属夹杂物S48CVOLVO图", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
